name = "BayesianShockEstimation"
uuid = "aa969ce8-6179-40db-adb7-88cfce5cdb65"
authors = ["Helmuth Naumer <hnaumer2@illinois.edu> and contributors"]
version = "0.1.0"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
